[packaging]
package_name = "azure-attestation"
package_nspkg = "azure-nspkg"
package_pprint_name = "Attestation"
package_doc_id = "attestation"
is_stable = false
is_arm = false
need_msrestazure = true
